### ISSUE TITLE
Version 2.4.X and Vine with Python2.7 support

### ISSUE THREAD

**Issue by belug23** [celery/py-amqp#275] opened 2019-05-15 12:46 UTC
While installing amqp 2.4.2 in a python 2.7 environnement, we got an incompatibility error, the way the requirements are done, amqp installs vine 5.0.0a1 which doesn't support python2.7 anymore.

See https://github.com/celery/py-amqp/blob/v2.4.2/requirements/default.txt#L1

The correction definition would be something like `vine>=1.1.3,<5.0.0` and the package would still support 2.7.

Thanks

**Comment by moggers87** [comment] 2019-06-03 17:34
What are you using to install amqp? Pip doesn't install alpha releases by default:

```
(amqp-test) [moggers@youngteazer amqp-test]$ python --version
Python 2.7.16
(amqp-test) [moggers@youngteazer amqp-test]$ pip --version
pip 19.1.1 from /dev/shm/amqp-test/lib/python2.7/site-packages/pip (python 2.7)
(amqp-test) [moggers@youngteazer amqp-test]$ pip install "amqp==2.4.2"
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting amqp==2.4.2
  Using cached https://files.pythonhosted.org/packages/42/ec/cbbaa8f75be8cbd019afb9d63258e2bdc95242f8c46a54bb90db5fef03bd/amqp-2.4.2-py2.py3-none-any.whl
Collecting vine>=1.1.3 (from amqp==2.4.2)
  Using cached https://files.pythonhosted.org/packages/7f/60/82c03047396126c8331ceb64da1dc52d4f1317209f32e8fe286d0c07365a/vine-1.3.0-py2.py3-none-any.whl
Installing collected packages: vine, amqp
Successfully installed amqp-2.4.2 vine-1.3.0
(amqp-test) [moggers@youngteazer amqp-test]$ pip freeze
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
amqp==2.4.2
vine==1.3.0
```

**Comment by thedrow** [comment] 2019-06-06 14:12
Yup, it shouldn't install it.

**Comment by thedrow** [comment] 2019-06-10 15:24
This is definitely not a bug.
I'm going to close this now.

Feel free to comment if you feel otherwise.

**Closed by thedrow** 2019-06-10 15:24 UTC
