### ISSUE TITLE
Upgrade issue: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 1

### ISSUE THREAD

**Issue by akanstantsinau** [celery/py-amqp#308] opened 2020-02-13 17:44 UTC
Hello

During upgrade Celery from:
amqp==1.4.9
celery==3.1.25
kombu==3.0.37
To:
amqp==2.5.2
celery==4.3.0
kombu==4.6.7

And having some task producers continue using old celery version at the moment when worker starts,
Following error occurs when celery worker starts:

```UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 1: invalid start byte
Error on stopping Gossip: UnicodeDecodeError('utf-8', b'N\xfd\x17=\x00\x00', 1, 2, 'invalid start byte')
Traceback (most recent call last):
  File "/lib/python3.6/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/lib/python3.6/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/lib/python3.6/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 364, in create_loop
    cb(*cbargs)
  File "/lib/python3.6/site-packages/kombu/transport/base.py", line 238, in on_readable
    reader(loop)
  File "/lib/python3.6/site-packages/kombu/transport/base.py", line 220, in _read
    drain_events(timeout=0)
  File "/lib/python3.6/site-packages/amqp/connection.py", line 505, in drain_events
    while not self.blocking_read(timeout):
  File "/lib/python3.6/site-packages/amqp/connection.py", line 511, in blocking_read
    return self.on_inbound_frame(frame)
  File "/lib/python3.6/site-packages/amqp/method_framing.py", line 59, in on_frame
    msg.inbound_header(buf)
  File "/lib/python3.6/site-packages/amqp/serialization.py", line 561, in inbound_header
    self._load_properties(class_id, buf, offset)
  File "/lib/python3.6/site-packages/amqp/serialization.py", line 519, in _load_properties
    props, offset = classes[class_id](buf, offset)
  File "/lib/python3.6/site-packages/amqp/serialization.py", line 421, in decode_properties_basic
    _f, offset = loads('F', buf, offset)
  File "/lib/python3.6/site-packages/amqp/serialization.py", line 225, in loads
    key = pstr_t(buf[offset:offset + keylen])
  File "/lib/python3.6/site-packages/amqp/utils.py", line 80, in bytes_to_str
    return s.decode('utf-8', 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 1: invalid start byte```

**Comment by thedrow** [comment] 2020-02-16 12:22
We can't reproduce this problem without more information.

**Comment by akanstantsinau** [comment] 2020-02-24 18:01
Found the root cause for the issue.
There was unexpected librabbitmq==1.6.1 in Celery beat instance. Also only this instance was using py2.

Assume that I should close this issue, as it is caused by using too old libraries.

Thanks!

**Comment by matusvalo** [comment] 2020-11-07 22:21
Closing this issue since explained above.

**Closed by matusvalo** 2020-11-07 22:21 UTC
